export type AlarmCodeOption = {
  code: number;
  label: string;
};

export const HOWEN_ALARM_CODE_OPTIONS: AlarmCodeOption[] = [
  { code: 0, label: "Desconocido" },
  { code: 1, label: "Perdida de video" },
  { code: 2, label: "Deteccion de movimiento" },
  { code: 3, label: "Video cubierto" },
  { code: 4, label: "Entrada de alarma activada" },
  { code: 5, label: "Alarma de emergencia" },
  { code: 6, label: "Alarma de baja velocidad" },
  { code: 7, label: "Alarma de alta velocidad" },
  { code: 8, label: "Alarma de baja temperatura" },
  { code: 9, label: "Alarma de alta temperatura" },
  { code: 10, label: "Alarma de humedad" },
  { code: 11, label: "Exceso de tiempo estacionado" },
  { code: 12, label: "Alarma de vibracion" },
  { code: 13, label: "Geocerca electronica" },
  { code: 14, label: "Ruta electronica" },
  { code: 15, label: "Apertura/cierre de puerta anormal" },
  { code: 16, label: "Almacenamiento anormal" },
  { code: 17, label: "Conduccion con fatiga" },
  { code: 18, label: "Volumen de gas anormal" },
  { code: 19, label: "Encendido ilegal" },
  { code: 20, label: "Modulo de ubicacion anormal" },
  { code: 21, label: "Panel frontal abierto" },
  { code: 22, label: "RFID detectado" },
  { code: 23, label: "IBUTTON" },
  { code: 24, label: "Aceleracion brusca" },
  { code: 25, label: "Desaceleracion brusca" },
  { code: 26, label: "Prealarma de baja velocidad" },
  { code: 27, label: "Prealarma de alta velocidad" },
  { code: 28, label: "Alarma de voltaje" },
  { code: 29, label: "Estadistica de pasajeros" },
  { code: 30, label: "Alarma DMS/ADAS" },
  { code: 31, label: "ACC encendido" },
  { code: 32, label: "Ralenti" },
  { code: 33, label: "Antena GPS desconectada" },
  { code: 34, label: "Cortocircuito en antena GPS" },
  { code: 35, label: "Salida IO" },
  { code: 36, label: "Conexion CANBus anormal" },
  { code: 37, label: "Alarma de remolque" },
  { code: 38, label: "Desplazamiento en neutro" },
  { code: 39, label: "RPM demasiado altas" },
  { code: 40, label: "Movimiento del vehiculo" },
  { code: 41, label: "Inicio de viaje" },
  { code: 42, label: "En viaje" },
  { code: 43, label: "Fin de viaje" },
  { code: 44, label: "Recuperacion de ubicacion GPS" },
  { code: 45, label: "Video anormal" },
  { code: 101, label: "Advertencia de colision frontal" },
  { code: 102, label: "Advertencia de salida de carril" },
  { code: 103, label: "Vehiculo frontal demasiado cerca" },
  { code: 104, label: "Advertencia de colision con peaton" },
  { code: 105, label: "Alarma por cambio frecuente de carril" },
  { code: 106, label: "Alarma por violacion de marcas viales" },
  { code: 107, label: "Aceleracion fuerte" },
  { code: 108, label: "Frenado brusco" },
  { code: 109, label: "Incidente de reconocimiento de senal vial" },
  { code: 110, label: "Colision por velocidad relativa frontal (FCW)" },
  { code: 111, label: "Colision por velocidad absoluta frontal (HMW)" },
  { code: 112, label: "Salida de carril izquierdo (LDW_L)" },
  { code: 113, label: "Salida de carril derecho (LDW_R)" },
  { code: 114, label: "Alarma VB de colision frontal a baja velocidad" },
  { code: 115, label: "Alarma de fatiga al conducir" },
  { code: 116, label: "Alarma de llamada telefonica" },
  { code: 117, label: "Alarma por fumar" },
  { code: 118, label: "Alarma de conduccion distraida" },
  { code: 119, label: "Alarma por conductor anormal" },
  { code: 120, label: "Evento de cambio de conductor" },
  { code: 121, label: "Ojos cerrandose" },
  { code: 122, label: "Bostezo" },
  { code: 123, label: "Alarma de camara cubierta" },
  { code: 124, label: "Mirada a derecha e izquierda" },
  { code: 125, label: "Sin cinturon de seguridad" },
  { code: 126, label: "Sin conductor" },
  { code: 127, label: "Bebiendo agua" },
  { code: 128, label: "Cambiando conductor" },
  { code: 129, label: "Regreso del conductor" },
  { code: 130, label: "Gafas infrarrojas" },
  { code: 131, label: "Autenticacion de conductor exitosa" },
  { code: 132, label: "Autenticacion de conductor fallida" },
  { code: 133, label: "No se detecta rostro" },
  { code: 200, label: "Entrada a geocerca" },
  { code: 201, label: "Salida de geocerca" },
  { code: 202, label: "Exceso de velocidad en geocerca" },
  { code: 203, label: "Advertencia de exceso de velocidad en geocerca" },
  { code: 204, label: "Baja velocidad en geocerca" },
  { code: 205, label: "Advertencia de baja velocidad en geocerca" },
  { code: 207, label: "Motor encendido en geocerca" },
  { code: 208, label: "Motor apagado en geocerca" },
  { code: 209, label: "Tiempo excedido dentro de geocerca" },
  { code: 210, label: "Carga de combustible" },
  { code: 211, label: "Robo de combustible" },
  { code: 212, label: "Aceleracion brusca (gsensor)" },
  { code: 768, label: "Notificacion de fin de viaje" },
  { code: 769, label: "Notificacion de actualizacion" },
];

export const DEFAULT_SELECTED_ALARM_CODES = [118, 116, 121, 122, 115] as const;

const ALARM_CODE_LABEL_MAP = new Map<number, string>(
  HOWEN_ALARM_CODE_OPTIONS.map((item) => [item.code, item.label]),
);

export function alarmLabelFromCode(code: number): string | null {
  return ALARM_CODE_LABEL_MAP.get(code) ?? null;
}
